{
  "hash": "5467d3e939ad80a00d6fb9dbea136b42",
  "result": {
    "markdown": "---\ntitle: \"Randomized Controlled Trials\"\n---\n\n\n> ### **`Assignment 8:`**  \nGiven a set of Data about a randomized experiment run by an online shop. E-commerce websites frequently conduct numerous randomized experiments, commonly referred to as AB testing in a business context.\n\n1. Check whether the covariates are balanced across the groups. Use a plot to show it.  \n2. Run a regression to find the effect of chatbot on sales.  \n3. Find subgroup-specific effects by including an interaction. Compute a CATE for one exemplary group.  \n4. Use the outcome variable purchase and run a logistic regression and interpret the coefficient for chatbot.  \n\n### **Solution:**  \n\n1. Differences Plots: to check the balance of the covariates, their differences are plotted for both groups (with/ without chatbot).\n\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-1_6421b619c254465d8841b17e8ac95974'}\n\n```{.r .cell-code}\n#Load Library & data:\n\nlibrary(tidyverse)\n\n\nabtest_online <- readRDS(\"D:/OneDrive/Samantha/TUHH/1stsemester/Causal Data Science for Business Analytics (SE)/Causal_Data_Science_Data/abtest_online.rds\")\n\nhead(abtest_online)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ip\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"chatbot\"],\"name\":[2],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"previous_visit\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mobile_device\"],\"name\":[4],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"purchase\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"purchase_amount\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"161.88.211.70\",\"2\":\"TRUE\",\"3\":\"0\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"239.86.201.0\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"1\",\"6\":\"39.45626\"},{\"1\":\"35.90.22.130\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"219.176.193.3\",\"2\":\"FALSE\",\"3\":\"4\",\"4\":\"TRUE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"247.85.168.16\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"120.221.249.244\",\"2\":\"TRUE\",\"3\":\"2\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#Previous Visits difference plot:\ncompare_previsit <- \n  ggplot(abtest_online, \n         aes(x = chatbot, \n             y = previous_visit, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"Previous Visit\", title = \"Difference in previous visits\")\n\ncompare_previsit\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Mobile Device users difference plot:\ncompare_mobiledevice <- \n  ggplot(abtest_online, \n         aes(x = chatbot, \n             y = mobile_device, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"Mobile Device\", title = \"Difference in mobile users\")\n\ncompare_mobiledevice\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#Purchase difference plot:\ncompare_purchase <- \n  ggplot(abtest_online, \n         aes(x = chatbot, \n             y = purchase, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"Purchase\", title = \"Difference in purchases\")\n\ncompare_purchase\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n\n```{.r .cell-code}\n#Purchases amount difference plot:\ncompare_purchaseamount <- \n  ggplot(abtest_online, \n         aes(x = chatbot, \n             y = purchase_amount, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"Purchase Amount\", title = \"Difference in purchases amount\")\n\ncompare_purchaseamount\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-4.png){width=672}\n:::\n:::\n\n\nAs illustrated by the plots the covariates are not balanced.\n\n2. The effect of chatbot on sales:\n\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-2_a3be9ecf794576d91d4bc532dd593705'}\n\n```{.r .cell-code}\n#Linear Regression on Chatbot:\nlm_chatbot <- lm(purchase_amount ~ chatbot, data=abtest_online)\nsummary(lm_chatbot)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot, data = abtest_online)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -16.702 -14.478  -9.626  13.922  64.648 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  16.7017     0.8374  19.944  < 2e-16 ***\n#> chatbotTRUE  -7.0756     1.1796  -5.998 2.79e-09 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.65 on 998 degrees of freedom\n#> Multiple R-squared:  0.0348,\tAdjusted R-squared:  0.03383 \n#> F-statistic: 35.98 on 1 and 998 DF,  p-value: 2.787e-09\n```\n:::\n:::\n\n\nBy checking the estimate value, having a chatbot has a negative relation with the purchases amount (sales).\n\n3. Mobile users sub-group effect:\n\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-3_b74b06d1c84a8be5164ffa994eea5997'}\n\n```{.r .cell-code}\n#Linear Regression on Chatbot in interaction with mobile users:\nlm_chatbot_mobusr <- lm(purchase_amount ~ chatbot* mobile_device, data=abtest_online)\nsummary(lm_chatbot_mobusr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot * mobile_device, data = abtest_online)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#> -16.98 -14.54  -9.95  14.13  65.24 \n#> \n#> Coefficients:\n#>                               Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)                    16.9797     1.0152  16.725   <2e-16 ***\n#> chatbotTRUE                    -7.0301     1.4284  -4.922    1e-06 ***\n#> mobile_deviceTRUE              -0.8727     1.7987  -0.485    0.628    \n#> chatbotTRUE:mobile_deviceTRUE  -0.1526     2.5369  -0.060    0.952    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.66 on 996 degrees of freedom\n#> Multiple R-squared:  0.03534,\tAdjusted R-squared:  0.03244 \n#> F-statistic: 12.16 on 3 and 996 DF,  p-value: 8.034e-08\n```\n:::\n:::\n\n\nNegative estimate value indicates negative relation.\n\n4. Logistic regression of purchase on chatbot: \n\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-4_79de04e04b46fb637a454b9c357edbb3'}\n\n```{.r .cell-code}\nlogistic_regression <- glm(purchase ~ chatbot, family=binomial(link='logit'), abtest_online)\nsummary(logistic_regression)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> glm(formula = purchase ~ chatbot, family = binomial(link = \"logit\"), \n#>     data = abtest_online)\n#> \n#> Coefficients:\n#>             Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept) -0.01613    0.08981  -0.180    0.857    \n#> chatbotTRUE -0.98939    0.13484  -7.337 2.18e-13 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1329.1  on 999  degrees of freedom\n#> Residual deviance: 1273.3  on 998  degrees of freedom\n#> AIC: 1277.3\n#> \n#> Number of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\nThe estimate value for ChatbotTrue is negative which means that having a chatbot decreases the chances of purchasing from a user and the p-value is less than 0.5 meaning this has a statistically significant effect. $\\beta = -0.98939$ then $e^\\beta = e^{-0.98939} = 0.372$ and this means having a chatbot is associated with a $62.8\\% (1-0.372=0.628)$ reduction in the purchase possibility.  ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}